"window.opacity" = 1.0

[colors.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#00d5d5"
green = "#1bc4d1"
magenta = "#a9a1e1"
red = "#ec4e0f"
white = "#dfdfdf"
yellow = "#ecbe7b"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#1c1f24"
blue = "#008ff1"
cyan = "#38b5de"
green = "#80c721"
magenta = "#c678dd"
red = "#fb3f3e"
white = "#202328"
yellow = "#ecbe7b"

[colors.primary]
background = "#282c34"
foreground = "#1CBC9B"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.DoomOne.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#00d5d5"
green = "#1bc4d1"
magenta = "#a9a1e1"
red = "#ec4e0f"
white = "#dfdfdf"
yellow = "#ecbe7b"

[font.DoomOne.cursor]
cursor = "#528bff"
text = "CellBackground"

[font.DoomOne.normal]
black = "#1c1f24"
blue = "#008ff1"
cyan = "#38b5de"
green = "#80c721"
magenta = "#c678dd"
red = "#fb3f3e"
white = "#202328"
yellow = "#ecbe7b"

[font.DoomOne.primary]
background = "#282c34"
foreground = "#1CBC9B"

[font.DoomOne.selection]
background = "#3e4451"
text = "CellForeground"

[font.bold]
family = "ComicPro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ComicPro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ComicPro Nerd Font"
style = "Italic"

[font.normal]
family = "ComicPro Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 0
