vim.cmd("colorscheme onedark")
-- vim.cmd("colorscheme tokyonight-night")

-- require("nightfox").setup({
-- 	palettes = {
-- 		nordfox = {
-- 			bg1 = "#282c34",
-- 			red = "#e06c75",
-- 			orange = "#d19a66",
-- 			yellow = "#e5c07b",
-- 			green = "#98c379",
-- 			cyan = "#56b6c2",
-- 			blue = "#61afef",
-- 			purple = "#c678dd",
-- 			white = "#abb2bf",
-- 			black = "#282c34",
-- 			gray = "#5c6370",
-- 		},
-- 	},
-- })
-- vim.cmd("colorscheme nordfox")
